!!python/object:argparse.Namespace
acc: 5 10 15
compiler_params_compile_mode: latency
config: config.yaml
dtype: f16
dump_default_config: false
enable_cascade_opt: false
hw: AIE
input_params_layouts:
- nchw
input_params_names:
- data
input_params_shapes:
- 1x3x224x224
input_params_types:
- rgb
jobs: 112
model_params_onnx_model: /mnt/user_home/jinzhao/work/ai_isp/model_zoo/project/insta_a300/insta_model/random_det_pkpt_head_pet_face_1183M_050e89a2.onnx
model_params_working_dir: ./model_output_dir
node_mem_max_size: 0
onnx: /mnt/user_home/jinzhao/work/ai_isp/model_zoo/project/insta_a300/insta_model/random_det_pkpt_head_pet_face_1183M_050e89a2.onnx
output: /mnt/user_home/jinzhao/work/model_to_sm/random_det_pkpt_head_pet_face_1183M_050e89a2_out
output_params_layouts:
- nchw
output_params_names:
- data
output_params_shapes:
- 1x3x224x224
output_params_types:
- bgr
partition_mode: auto
quant_config: null
quant_params_config_file: ''
shape: null
stage: binary
stride: 32
subnet_mem_size: 3.0
symbol_config: sv_ref
vbus_mode: false
ver: v2.0
